// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAubGS8kyxe3c9ire_-eDEQE_HC3iqAO7c',
    appId: '1:1054913341728:web:95329c0a05e919ac4f8f45',
    messagingSenderId: '1054913341728',
    projectId: 'medremind-2b578',
    authDomain: 'medremind-2b578.firebaseapp.com',
    storageBucket: 'medremind-2b578.firebasestorage.app',
    measurementId: 'G-LQQYE8KDTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB4_9dDqO3E3cwcqk_LZs9_ZJl9T_u8x4',
    appId: '1:1054913341728:android:8d01a5d0460509654f8f45',
    messagingSenderId: '1054913341728',
    projectId: 'medremind-2b578',
    storageBucket: 'medremind-2b578.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDvwzuYZACSUtFW-8cj104KB7rxaNcLjY',
    appId: '1:1054913341728:ios:9dc314484e4157894f8f45',
    messagingSenderId: '1054913341728',
    projectId: 'medremind-2b578',
    storageBucket: 'medremind-2b578.firebasestorage.app',
    iosBundleId: 'com.medremind.medremind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDvwzuYZACSUtFW-8cj104KB7rxaNcLjY',
    appId: '1:1054913341728:ios:9dc314484e4157894f8f45',
    messagingSenderId: '1054913341728',
    projectId: 'medremind-2b578',
    storageBucket: 'medremind-2b578.firebasestorage.app',
    iosBundleId: 'com.medremind.medremind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAubGS8kyxe3c9ire_-eDEQE_HC3iqAO7c',
    appId: '1:1054913341728:web:5f86c491861dff514f8f45',
    messagingSenderId: '1054913341728',
    projectId: 'medremind-2b578',
    authDomain: 'medremind-2b578.firebaseapp.com',
    storageBucket: 'medremind-2b578.firebasestorage.app',
    measurementId: 'G-9KXGXP1JP8',
  );
}
