class AppLocalizations {
  final String language;

  AppLocalizations(this.language);

  static const Map<String, Map<String, String>> _localizedValues = {
    'English': {
      'app_name': 'MedRemind',
      'good_morning': 'Good morning',
      'care_plan_subtitle': 'Here is your care plan for today.',
      'todays_schedule': "Today's Schedule",
      'due_now': 'DUE NOW',
      'log_dose': 'Log Dose',
      'daily_progress': 'Daily Progress',
      'taken': 'Taken',
      'missed': 'Missed',
      'upcoming': 'Upcoming',
      'as_needed': 'As Needed',
      'add_med': 'Add Med',
      'contact_support': 'Contact Support',
      'coming_up_next': 'Coming Up Next',
      'medications': 'Meds',
      'progress': 'Progress',
      'settings': 'Settings',
      'home': 'Home',
      'weekly_progress': 'Weekly Progress',
      'great_job': 'GREAT JOB!',
      'adherence_rate': 'Adherence Rate',
      'medication_heatmap': 'Medication Heatmap',
      'caregiver_support': 'Caregiver Support',
      'send_alert': 'Send Alert',
      'emergency_assistance': 'Emergency Assistance',
      'health_education': 'Health Education',
      'library_resources': 'Library & Resources',
      'app_preferences': 'App Preferences',
      'language': 'Language',
      'font_size': 'Font Size',
      'notification_sounds': 'Notification Sounds',
      'offline_mode': 'Offline Mode',
      'log_out': 'Log Out',
      'create_account': 'Create Account',
      'welcome_back': 'Welcome Back',
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'did_you_take': 'Did you take',
      'yes_i_took_it': 'Yes, I took it',
      'skip_this_dose': 'Skip this dose',
    },
    'Kinyarwanda': {
      'app_name': 'MedRemind',
      'good_morning': 'Mwaramutse',
      'care_plan_subtitle': "Dore gahunda y'imiti yawe y'uyu munsi.",
      'todays_schedule': "Gahunda y'Uyu Munsi",
      'due_now': 'BAGEZE KO UWUFWATA',
      'log_dose': 'Andika Umuti',
      'daily_progress': 'Iterambere ry’Umunsi',
      'taken': 'Wafashwe',
      'missed': 'Wasibijwe',
      'upcoming': 'Utaha',
      'as_needed': 'Cyangwa ukenewe',
      'add_med': 'Ongeraho Umuti',
      'contact_support': 'Abamfasha',
      'coming_up_next': 'Umuti Ukurikiyeho',
      'medications': 'Imiti',
      'progress': 'Iterambere',
      'settings': 'Igenamiterere',
      'home': 'Ahabanza',
      'weekly_progress': "Iterambere ry'Icyumweru",
      'great_job': 'WAKOZE NEZA!',
      'adherence_rate': 'Igipimo cyo Kwikorera',
      'medication_heatmap': 'Ikarita y’Imiti',
      'caregiver_support': 'Soutien aux aidants',
      'send_alert': 'Ohereza Alert',
      'emergency_assistance': 'Ubutabazi bw\'Ihitirwa',
      'health_education': 'Inyigisho z\'Ubuzima',
      'library_resources': 'Isomero n\'Ibyifashishwa',
      'app_preferences': 'Ibipimo by\'Porogaramu',
      'language': 'Ururimi',
      'font_size': 'Ingano y\'Inyuguti',
      'notification_sounds': 'Amajwi y\'Ibyatanzwe',
      'offline_mode': 'Uburyo bwa Offline',
      'log_out': 'Sohoka',
      'create_account': 'Kurema Konti',
      'welcome_back': 'Murakaza Neza',
      'sign_in': 'Kwinjira',
      'sign_up': 'Kwiyandikisha',
      'did_you_take': 'Wafashe',
      'yes_i_took_it': 'Yego, nawufashe',
      'skip_this_dose': 'Siba iyi dose',
    },
    'French': {
      'app_name': 'MedRemind',
      'good_morning': 'Bonjour',
      'care_plan_subtitle': 'Voici votre plan de soins pour aujourd’hui.',
      'todays_schedule': 'Programme d’aujourd’hui',
      'due_now': 'À PRENDRE MAINTENANT',
      'log_dose': 'Enregistrer la dose',
      'daily_progress': 'Progrès quotidien',
      'taken': 'Pris',
      'missed': 'Manqué',
      'upcoming': 'À venir',
      'as_needed': 'Au besoin',
      'add_med': 'Ajouter un médicament',
      'contact_support': 'Contacter le soutien',
      'coming_up_next': 'Prochaine prise',
      'medications': 'Médicaments',
      'progress': 'Progrès',
      'settings': 'Paramètres',
      'home': 'Accueil',
      'weekly_progress': 'Progrès hebdomadaire',
      'great_job': 'BRAVO !',
      'adherence_rate': 'Taux d’observance',
      'medication_heatmap': 'Carte d’observance',
      'caregiver_support': 'Soutien aux aidants',
      'send_alert': 'Envoyer une alerte',
      'emergency_assistance': 'Assistance d’urgence',
      'health_education': 'Éducation à la santé',
      'library_resources': 'Bibliothèque & Ressources',
      'app_preferences': 'Préférences de l’application',
      'language': 'Langue',
      'font_size': 'Taille de la police',
      'notification_sounds': 'Sons de notification',
      'offline_mode': 'Mode hors ligne',
      'log_out': 'Se déconnecter',
      'create_account': 'Créer un compte',
      'welcome_back': 'Bon retour',
      'sign_in': 'Se connecter',
      'sign_up': 'S’inscrire',
      'did_you_take': 'Avez-vous pris',
      'yes_i_took_it': 'Oui, je l’ai pris',
      'skip_this_dose': 'Sauter cette dose',
    },
    'Swahili': {
      'app_name': 'MedRemind',
      'good_morning': 'Habari ya asubuhi',
      'care_plan_subtitle': 'Huu hapa mpango wako wa afya wa leo.',
      'todays_schedule': 'Ratiba ya Leo',
      'due_now': 'INATAKIWA SASA',
      'log_dose': 'Hifadhi Dawa',
      'daily_progress': 'Maendeleo ya Kila Siku',
      'taken': 'Imechukuliwa',
      'missed': 'Iliyokosa',
      'upcoming': 'Inayokuja',
      'as_needed': 'Inapohitajika',
      'add_med': 'Ongeza Dawa',
      'contact_support': 'Msaada wa Wasaidizi',
      'coming_up_next': 'Inayofuata',
      'medications': 'Dawa',
      'progress': 'Maendeleo',
      'settings': 'Mipangilio',
      'home': 'Nyumbani',
      'weekly_progress': 'Maendeleo ya Wiki',
      'great_job': 'KAZI NZURI!',
      'adherence_rate': 'Kiwango cha Ufuataji',
      'medication_heatmap': 'Ramani ya Dawa',
      'caregiver_support': 'Msaada wa Wasaidizi',
      'send_alert': 'Tuma Tahadhari',
      'emergency_assistance': 'Msaada wa Dharura',
      'health_education': 'Elimu ya Afya',
      'library_resources': 'Maktaba & Rasilimali',
      'app_preferences': 'Mapendeleo ya Programubodi',
      'language': 'Lugha',
      'font_size': 'Ukubwa wa Maandishi',
      'notification_sounds': 'Sauti za Arifa',
      'offline_mode': 'Njia ya Nje ya Mtandao',
      'log_out': 'Ondoka',
      'create_account': 'Fungua Akaunti',
      'welcome_back': 'Karibu Tena',
      'sign_in': 'Ingia',
      'sign_up': 'Jiandikishe',
      'did_you_take': 'Je, umechukua',
      'yes_i_took_it': 'Ndiyo, nimechukua',
      'skip_this_dose': 'Ruka kipimo hiki',
    },
  };

  String translate(String key) {
    return _localizedValues[language]?[key] ??
        _localizedValues['English']?[key] ??
        key;
  }

  static AppLocalizations of(String language) {
    return AppLocalizations(language);
  }
}
